name: Python Syntax & Format Validation and Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-python: '3.11'

    - name: Lint Check
      run: |
        # Check for syntax errors or undefined names
        python3 -m compileall .

    - name: Run Modular Integration Tests
      run: |
        python3 -m unittest test_parser.py
